//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexRequest", Namespace="http://schemas.datacontract.org/2004/07/LearnMVC.WebServices")]
    [System.SerializableAttribute()]
    public partial class ComplexRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexResponse", Namespace="http://schemas.datacontract.org/2004/07/LearnMVC.WebServices")]
    [System.SerializableAttribute()]
    public partial class ComplexResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="ServiceReference1.FileConverter")]
    public interface FileConverter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileConverter/GetInt", ReplyAction="http://tempuri.org/FileConverter/GetIntResponse")]
        int GetInt(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileConverter/ComplexMethod", ReplyAction="http://tempuri.org/FileConverter/ComplexMethodResponse")]
        LearnMVC.ServiceReference1.ComplexResponse ComplexMethod(LearnMVC.ServiceReference1.ComplexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileConverter/UploadFile", ReplyAction="http://tempuri.org/FileConverter/UploadFileResponse")]
        bool UploadFile();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileConverterChannel : LearnMVC.ServiceReference1.FileConverter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileConverterClient : System.ServiceModel.ClientBase<LearnMVC.ServiceReference1.FileConverter>, LearnMVC.ServiceReference1.FileConverter {
        
        public FileConverterClient() {
        }
        
        public FileConverterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileConverterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileConverterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileConverterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetInt(int i) {
            return base.Channel.GetInt(i);
        }
        
        public LearnMVC.ServiceReference1.ComplexResponse ComplexMethod(LearnMVC.ServiceReference1.ComplexRequest request) {
            return base.Channel.ComplexMethod(request);
        }
        
        public bool UploadFile() {
            return base.Channel.UploadFile();
        }
    }
}
